language: node_js
node_js:
  - "lts/*"

before_install:
  - echo "$GIT_RSA" > ~/.ssh/id_rsa
  - chmod +x publi.sh
  
script:
  - "npm run eslint"
  - if [ "$TRAVIS_BRANCH" == "production" ]; then ./publi.sh; fi


