language: node_js
node_js:
  - "lts/*"

before_install:
  - openssl aes-256-cbc -K $encrypted_06e82094c74d_key -iv $encrypted_06e82094c74d_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - chmod +x publi.sh
  
script:
  - "npm run eslint"
  - if [ "$TRAVIS_BRANCH" == "production" ]; then ./publi.sh; fi


